### ISSUE TITLE
z3 opam

### ISSUE THREAD

**Issue by spitters** [EasyCrypt/easycrypt#56] opened 2021-03-17 13:34 UTC
I'm following the instructions here, but instead I'm installing z3 from opam.
https://github.com/EasyCrypt/easycrypt#installing-requirements-using-opam-posix-systems

This works with the package z3-prover from an older repo: https://github.com/EasyCrypt/opam/tree/master/, but the default z3 opam package does not work for me.

One hint might be that
```
easycrypt why3config
```
looks in: ~/.config/easycrypt/why3
but why3 config --detect does not.

Something similar may be going on in [this tweet](https://twitter.com/chelseakomlo/status/1371930968471130112?s=20)

**Comment by fdupress** [comment] 2021-03-17 13:42
Not sure what you'd like us to fix, here: our installation instructions work, your deviation from them does not—note in particular that the older repo you link to no longer even exists. Does everything work as expected if you download z3 through official sources?

**Comment by alleystoughton** [comment] 2021-03-17 13:47
I think the problem is that it's not clear how to figure out what versions of Alt-Ergo and Z3 are consistent with whatever the current version of Why3 (at some point in time). At present we could say run

opam install alt-ergo.2.3.1

(after making sure autoconf is installed) and then install version 4.8.6 of Z3. There are binaries for macOS (osx) and Ubuntu Linux at this URL https://github.com/Z3Prover/z3/releases/tag/z3-4.8.6.

What do we write that's not version specific?

(Cf., my instructions to students at https://alleystoughton.us/easycrypt-installation.html.)

Alley

**Comment by spitters** [comment] 2021-03-17 13:49
Agreed, nothing is "wrong". It's just slightly confusing that z3 has official opam packages, but that that installation apparently does not work out of the box. It would be easier. Don't you agree? I'd be happy to report upstream, if I can figure out why this does not work.

**Comment by spitters** [comment] 2021-03-17 13:57
@alleystoughton the other issue is that opam sometimes works badly with libraries that are already installed by another package manager. z3 4.8.7 is in ubuntu. Would it make sense to recommend using either package manager (apt or opam)

**Comment by strub** [comment] 2021-03-17 14:01
> I'm following the instructions here, but instead I'm installing z3 from opam.
> https://github.com/EasyCrypt/easycrypt#installing-requirements-using-opam-posix-systems

> This works with the package z3-prover from an older repo

We used to maintain the "z3-prover" opam package, but  we have disbanded it several years ago and should not be used or referred to anymore. I don't even understand where you found it. Currently, the README file recommends to download Z3 from official sources.

> but the default z3 opam package does not work for me.

This package only installs the OCaml bindings for the Z3 library. Please, do contact the maintainer if you think that the package's synopsis should warn about that.

> easycrypt why3config

This command executes (verbatim)

```
why3 config --detect --full-config
```

If you configured EasyCrypt to use a Why3 configuration file different from the default one, it will add the relevant flags to `why3 config`.

> looks in: ~/.config/easycrypt/why3

It does not look in `~/.config/easycrypt/why3` by default. However, you may have an `easycrypt.ini` in `~/.config/easycrypt` that changes the default why3 configuration file.

> but why3 config --detect does not.

You are missing a `--full-config`. This is why I added an `easycrypt why3config` - the Why3 CLI is a quite moving target recently.

**Comment by strub** [comment] 2021-03-17 14:08
@alleystoughton François is currently updating the README file to take this into consideration.

@spitters Yes, we can add a sentence that we you can install provers using official binary packages, from source, using your preferred package manager.

**Comment by fdupress** [comment] 2021-03-17 14:09
@spitters can you check the current HEAD and tell me if it helps with the prover version mess Why3 and the solvers get themselves into?

Do note that z3 4.8.7 is not known to work with the current why3 release, so I'd probably avoid using the ubuntu package.

**Comment by spitters** [comment] 2021-03-17 14:35
Many thanks for the prompt responses. @fdupress yes, 4.8.7 seems to be the issue. (Both cvc4 and z3 installed from Ubuntu)
```
why3 config --detect --full-config
Found prover CVC4 version 1.6 (alternative: counterexamples)
Found prover CVC4 version 1.6, OK.
Found prover Coq version 8.11.0, but no Why3 libraries were compiled for it
Prover CVC4 version 1.6 is not known to be supported.
Known versions for this prover: 1.7.
Known old versions for this prover: .
Prover Z3 version 4.8.7 is not known to be supported.
Known versions for this prover: 4.8.0, 4.8.1, 4.8.3, 4.8.4, 4.8.5, 4.8.6.
Known old versions for this prover: .
13 prover(s) added (including 2 prover(s) with an unrecognized version)
Generating strategies:
  Prover CVC4 1.6 will be used in Auto level >= 1

**Comment by spitters** [comment] 2021-03-17 15:13
@fdupress Thanks! I've cleaned up and removed the ubuntu versions on z3 and cvc4. 
I now have z3 4.8.6 from opam.

I'm still having issues, though.
Note that: 2.3.2 of alt-ergo is not supported by Why3 version 1.3.3. 
```
why3 config --detect --full-config
Found prover Coq version 8.11.0, but no Why3 libraries were compiled for it
Prover Alt-Ergo version 2.3.2 is not known to be supported.
Known versions for this prover: 2.3.1, 2.3.0.
Known old versions for this prover: .
17 prover(s) added (including 1 prover(s) with an unrecognized version)

**Comment by spitters** [comment] 2021-03-17 15:24
Version 1.4.0 of why3 supports all these newer versions. :tada: 
https://gitlab.inria.fr/why3/why3/-/blob/master/CHANGES.md

Unfortunately, an opam package still seems to be missing. @silene do you happen to when this will be released?
https://opam.ocaml.org/packages/why3/

**Comment by silene** [comment] 2021-03-17 15:51
> do you happen to when this will be released?

The pull request was submitted on Saturday. So, hopefully not too long.

**Comment by spitters** [comment] 2021-03-17 16:09
https://github.com/ocaml/opam-repository/pull/18327

**Comment by fdupress** [comment] 2021-03-17 20:19
I'm closing this, since this particular issue of more clearly identifying which smt solvers currently work with easycrypt/why3 is solved.

@spitters Moving to Why3 1.4.0 might take a bit of time even after it makes its way to the opam repo: there's a few breaking changes.

**Closed by fdupress** 2021-03-17 20:19 UTC
